---
queryId: LW_Custom_PublicIpAddress_and_open
queryText: |-
  {
      source {
          LW_CFG_AWS_EC2_INSTANCES instances,
          array_to_rows(instances.RESOURCE_CONFIG:SecurityGroups) as (security_groups)
      }
      filter {
          security_groups:GroupId::string in {
              source {
                  LW_CFG_AWS_EC2_SECURITY_GROUPS a,
                  array_to_rows(a.RESOURCE_CONFIG:IpPermissions) as (ip_permissions),
                  array_to_rows(ip_permissions:IpRanges) as (ip_ranges)
              }
              filter {
                  ip_permissions:IpProtocol = 'tcp'
                  and (ip_permissions:FromPort <= 22 and ip_permissions:ToPort >= 22)
                  and ip_ranges:CidrIp = '0.0.0.0/0'
              }
              return distinct {
                  RESOURCE_ID
              }
          }
          and value_exists(instances.RESOURCE_CONFIG:PublicIpAddress)
      }
      return distinct {
          ACCOUNT_ALIAS,
          ACCOUNT_ID,
          ARN as RESOURCE_KEY,
          RESOURCE_REGION,
          RESOURCE_TYPE,
          SERVICE,
          'SGUnrestricted22IngressPublicIp' as COMPLIANCE_FAILURE_REASON
      }
  }
